version: "3.7"
services:

  controlservice:
    build: 
      context: ./control_service
    container_name: "controlservice"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controlservice.rule=Host(`controlservice.isolatedshopping.me`)"
      #- "traefik.http.routers.controlservice.rule=Host(`controlservice.localhost`)" 
      - "traefik.http.services.controlservice.loadbalancer.server.port=5000"
      - "traefik.http.routers.controlservice.entrypoints=web"
    networks:
      - "this"
  
  inputservice:
    build: 
      context: ./input_service
    container_name: "inputservice"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inputservice.rule=Host(`inputservice.isolatedshopping.me`)"
      #- "traefik.http.routers.inputservice.rule=Host(`inputservice.localhost`)" 
      - "traefik.http.services.inputservice.loadbalancer.server.port=5000"
      - "traefik.http.routers.inputservice.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"

    networks:
      - "this"

  proxy:
    image: "traefik:v2.1"
    container_name: "proxy"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" #NOT IN PRODUCTION PLEASE
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.email=squallhalle@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.mytlschallenge.acme.storage=acme.json
      - "--certificatesresolvers.mytlschallenge.acme.dnschallenge=true
      - "--certificatesresolvers.mytlschallenge.acme.dnschallenge.provider=route53
      - "--certificatesresolvers.mytlschallenge.acme.dnsChallenge.delayBeforeCheck=0
    ports:
      - "80:80"
      - "433:443"
      - "8081:8080" #NOT IN PRODUCTION PLEASE
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - "this"


### this container should help you to determinate if everything works.
  helloweb:
    image: "nginx"
    container_name: "helloweb"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.helloweb.rule=Host(`test.isolatedshopping.me`)"
      #- "traefik.http.routers.helloweb.rule=Host(`test.localhost`)" 
      #- "traefik.http.routers.helloweb.entrypoints=web"
      - "traefik.http.routers.helloweb.entrypoints=websecure"
      - "traefik.http.routers.helloweb.tls=true"
      - "traefik.http.routers.helloweb.tls.certresolver=mytlschallenge"
    networks:
      - "this"

networks:
    this:
     name: backend
     driver: bridge

