version: "3.7"
services:

  controlservice:
    image: wirvsvirus17livetracking/controlservice
    #build: 
    #  context: ./control_service
    container_name: "controlservice"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controlservice.rule=Host(`controlservice.sicher-einkaufen.info`)"
    #- "traefik.http.routers.controlservice.rule=Host(`controlservice.localhost`)" 
      - "traefik.http.services.controlservice.loadbalancer.server.port=5000"
      - "traefik.http.routers.controlservice.entrypoints=websecure"
      - "traefik.http.routers.controlservice.tls.certresolver=myresolver"
      - "traefik.http.routers.controlservice-redirect.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.inpcontrolserviceutservice-redirect.middlewares=controlservice-redirect"
      - "traefik.http.middlewares.controlservice-redirect.redirectscheme.scheme=https"


    networks:
      - "this"
  
  inputservice:
    image: wirvsvirus17livetracking/inputservice:dev
    #build: 
    #  context: ./input_service
    container_name: "inputservice"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inputservice.rule=Host(`inputservice.sicher-einkaufen.info`)"
      #- "traefik.http.routers.inputservice.rule=Host(`inputservice.localhost`)" 
      - "traefik.http.services.inputservice.loadbalancer.server.port=5000"
      - "traefik.http.routers.inputservice.entrypoints=websecure"
      - "traefik.http.routers.inputservice.tls.certresolver=myresolver"
      - "traefik.http.routers.inputservice-redirect.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.inputservice-redirect.middlewares=inputservice-redirect"
      - "traefik.http.middlewares.inputservice-redirect.redirectscheme.scheme=https"
    networks:
      - "this"

  client:
      image: niewview/supermarket_clientapp
        #build: 
        #  context: ./Supermarkt_LiveTracker/ClientApp
      container_name: "client"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.client.rule=Host(`sicher-einkaufen.info`)"
        #- "traefik.http.routers.helloweb.rule=Host(`test.localhost`)" 
        - "traefik.http.routers.client.entrypoints=websecure"
        - "traefik.http.routers.client.tls.certresolver=myresolver"
        - "traefik.http.routers.client-redirect.rule=HostRegexp(`{any:.*}`)"
        - "traefik.http.routers.client-redirect.middlewares=client-redirect"
        - "traefik.http.middlewares.client-redirect.redirectscheme.scheme=https"
      networks:
        - "this"


  proxy:
    image: "traefik:v2.1"
    container_name: "proxy"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" #NOT IN PRODUCTION PLEASE
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"  #comment me out for production 
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=squallhalle@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" #NOT IN PRODUCTION PLEASE
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - "this"




networks:
    this:
     name: backend
     driver: bridge


