version: "3.7"
services:

  controlservice:
    build: 
      context: ./control_service
    container_name: "controlservice"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controlservice.rule=Host(`controlservice.isolatedshopping.me`)"
      #- "traefik.http.routers.controlservice.rule=Host(`controlservice.localhost`)" 
      - "traefik.http.services.controlservice.loadbalancer.server.port=5000"
      - "traefik.http.routers.controlservice.entrypoints=websecure"
      - "traefik.http.routers.controlservice.tls.certresolver=myresolver"


    networks:
      - "this"
  
  inputservice:
    build: 
      context: ./input_service
    container_name: "inputservice"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inputservice.rule=Host(`inputservice.isolatedshopping.me`)"
      #- "traefik.http.routers.inputservice.rule=Host(`inputservice.localhost`)" 
      - "traefik.http.services.inputservice.loadbalancer.server.port=5000"
      - "traefik.http.routers.inputservice.entrypoints=websecure"
      - "traefik.http.routers.inputservice.tls.certresolver=myresolver"

    networks:
      - "this"

  proxy:
    image: "traefik:v2.1"
    container_name: "proxy"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" #NOT IN PRODUCTION PLEASE
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"  #comment me out for production 
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=squallhalle@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      ###
      - "traefik.http.middlewares.redirect.redirectregex.regex="^http://(.*)"
      - "traefik.http.middlewares.redirect.redirectregex.replacement="https://\$1"
      - "traefik.http.routers.web-redirect.rule="Host(\`domain.com\`)"
      - "traefik.http.routers.web-redirect.entrypoints="web"
      - "traefik.http.routers.web-redirect.middlewares="redirect"
      - "traefik.http.routers.web-secure.entrypoints="websecure"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" #NOT IN PRODUCTION PLEASE
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - "this"


### this container should help you to determinate if everything works.
  helloweb:
    image: "nginx"
    container_name: "helloweb"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helloweb.rule=Host(`test.isolatedshopping.me`)"
      #- "traefik.http.routers.helloweb.rule=Host(`test.localhost`)" 
      - "traefik.http.routers.helloweb.entrypoints=websecure"
      - "traefik.http.routers.helloweb.tls.certresolver=myresolver"
    networks:
      - "this"

networks:
    this:
     name: backend
     driver: bridge

